package com.example.kotlindersleri.degiskenler

fun main() {
    var sehir = "Kazablanka"
    println("Şehir = $sehir")
    var ulke = "Fas"
    println("Ülke = $ulke")
    val telefon = 5435465210
    println("Telefon = $telefon")
    var postaKodu = 34500
    println("Posta Kodu = $postaKodu")
    val email = "okyanusodabas@hotmail.com"
    println("Email = $email")
    var meslek = "Yazılım Mühendisliği"
    println("Meslek = $meslek")
    var stokMiktari = 1000
    println("Stokdaki Ürün Miktarı = $stokMiktari")
    val musteriAdi = "Okyanus"
    println("Müşterinin Adı = $musteriAdi")
    var bakiye = 35000
    println("Bakiye = $bakiye")
    val dogumGunu = "26 Ağustos 2004"
    println("Doğum Günü = $dogumGunu")
    var maas = 56000
    println("Maaş = $maas")
    var medeniDurum = "Evli"
    println("Medeni Durum = $medeniDurum")
    var urunYorum = true
    println("Ürünlere Yorum = $urunYorum")
    var odemeTarihi = "22 Haziran"
    println("Ödeme Tarihi = $odemeTarihi")
    var odeme = "Kredi Kartı"
    println("Ödeme = $odeme")
    var siparisAdeti = 890
    println("Sipariş Adeti = $siparisAdeti")
    var arabaModel = "Kia Sorento"
    println("Araba Model = $arabaModel")
    var kitapAdi= "Fareler ve İnsanlar"
    println("Kitap Adı = $kitapAdi")
    var yayınTarih = "11.02.1956"
    println("Yayın Tarihi = $yayınTarih")
    var indirimMiktari = 120
    println("İndirim Miktarı = $indirimMiktari")
    var odaSayisi = 500
    println("Oda Sayısı = $odaSayisi")
    val enlem = "90 derece"
    println("Enlem = $enlem")
    val boylam = "-45 derece"
    println("Boylam = $boylam")
    var urunAdi= "Nike Airmax"
    println("Ürün Adı = $urunAdi")
    var yemekFiyati = 250
    println("Yemek Fiyatı = $yemekFiyati")
    var marka = "Apple"
    println("Marka = $marka")
    var muzikAdi = "Bohemian Rhapsody"
    println("Müzik Adı = $muzikAdi")
    var videoSuresi = "3 dakika 45 saniye"
    println("Video Süresi = $videoSuresi")
    var urunPuani = 4.8
    println("Ürün Puanı = $urunPuani")
    var resimAdi = "manzara.jpg"
    println("Resim Adı = $resimAdi")
    var dosyaFormati = "PDF"
    println("Dosya Formatı = $dosyaFormati")
    var renk = "Mavi"
    println("Renk = $renk")
    var renkKodu = "#0000FF"
    println("Renk Kodu = $renkKodu")
    var telefonModeli = "iPhone 15 Pro"
    println("Telefon Modeli = $telefonModeli")
    var ekranBoyutu = "6.1 inç"
    println("Ekran Boyutu = $ekranBoyutu")
    var agirlik = "190 gram"
    println("Ağırlık = $agirlik")
    var ulusalGun = "23 Nisan"
    println("Ulusal Gün = $ulusalGun")
    var tatilGunu = "Cumartesi"
    println("Tatil Günü = $tatilGunu")
    var rezervasyonTarihi = "01 Mayıs 2025"
    println("Rezervasyon Tarihi = $rezervasyonTarihi")
    var sokakAdi = "İnönü Caddesi"
    println("Sokak Adı = $sokakAdi")
    var otobusHatti = "34AS"
    println("Otobüs Hattı = $otobusHatti")
    var kalanDakika = 15
    println("Kalan Dakika = $kalanDakika")
    var takipKodu = "TR123456789"
    println("Takip Kodu = $takipKodu")
    var kuponSuresi = "30 gün"
    println("Kupon Süresi = $kuponSuresi")
    var kuponKodu = "YAZ2025"
    println("Kupon Kodu = $kuponKodu")
    var faturaAdresi = "Kazablanka, Fas"
    println("Fatura Adresi = $faturaAdresi")


}